apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: quake
    database: earthquakes
    secureJsonData:
      password: quakepass
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15